### ISSUE TITLE
Possible bug with counting update queries in verification

### ISSUE THREAD

**Issue by billywhizz** [TechEmpower/TFBVerifier#4]
Hi,

I have been doing some local testing with the new TFBToolet tool and have come across an issue that seems like a bug in the tool to me.

According to the requirements here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#database-updates, it is ok to do the updates in a single query, as long as the selects happen individually. A number of frameworks (including mine) are taking advantage of this to improve performance.

I have tested the following frameworks which are all failing the "verify" check for updates with the same error:
- [drogon-core](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/drogon/drogon_benchmark/controllers/UpdatesCtrlRaw.cc#L16)
- [ntex-db](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/ntex/src/db.rs#L46)
- [just](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/just/techempower.js#L45)
- [lithium-postgres-batch](https://github.com/matt-42/lithium/blob/master/single_headers/lithium_pgsql.hh#L2657)

The error I see is:
Only 21840 executed queries in the database out of roughly 40960 expected

The command I ran was:
```
./tfb_toolset --type update -t {framework} -m verify
```

I have added some debugging to my code to try to see why this is happening. When checking the statuses coming back from postgres, i can see the updated rows count adds up to what should be expected so i don't think there is an issue with my framework. This would be backed up by all the other frameworks (which I have tested) which use the batched update technique also failing in the same way on this test.

I think it is likely something to do with the concurrency on the [thread pool](https://github.com/TechEmpower/TFBVerifier/blob/master/src/database/mod.rs#L152) - maybe a race condition? i am not that very familiar with rust so hard to tell without some further digging.

You can see that it works fine if i only use a concurrency of 8 (the number of available threads on the machine i am testing on) but as soon as i go above 8 i see the error.

```
./tfb_toolset --concurrency-levels 8 --query-levels 20 --type update -t just -m verify
```
![tfb-concurrency-8](https://user-images.githubusercontent.com/159073/96800828-2f3bc800-13fe-11eb-8d29-19f4ef5388e6.png)

```
./tfb_toolset --concurrency-levels 9 --query-levels 20 --type update -t just -m verify
```
![tfb-concurrency-9](https://user-images.githubusercontent.com/159073/96800838-36fb6c80-13fe-11eb-89cb-ae959d7a47f8.png)

**Comment by msmith-techempower** [comment]
Great error report. I will check this out first thing tomorrow morning. The verifier implementation is basically brand new and took me a *lot* of iteration getting it working based on core-count; therefore, I have every reason to believe that I got this wrong and this is a bug. 

I will report back when I know more. Cheers!

**Comment by msmith-techempower** [comment]
Oh, before I forget - these are all database-specific, so which database were you testing against (although, if it is a bug, it will likely be a bug for all of them since I tried to implement them the same)?

**Comment by billywhizz** [comment]
> Oh, before I forget - these are all database-specific, so which database were you testing against (although, if it is a bug, it will likely be a bug for all of them since I tried to implement them the same)?

postgres. here is the config.toml i used for my framework. similar for the others. you will need to update the Dockerfile to expose the port as that change has not been committed yet.

```
[framework]
name = "just"
authors = ["TechEmpower <dev@techempower.com>"]
github = "https://github.com/just-js/just"

[main]
urls.json = "/json"
urls.plaintext = "/plaintext"
urls.db = "/db"
urls.query = "/query?q="
urls.cached_query = "/cached-world?q="
urls.fortune = "/fortunes"
urls.update = "/update?q="
approach = "Realistic"
classification = "Platform"
database = "Postgres"
orm = "Raw"
platform = "just-js"
webserver = "just-js"
os = "Linux"
database_os = "Linux"
versus = "nodejs"

```

**Comment by billywhizz** [comment]
also, i tested againt the "fiber" framework and it worked fine so is likely only these frameworks that are doing bulk updates which are having the issue. maybe the calculations for expected rows affected are not taking this into account.

**Comment by msmith-techempower** [comment]
I tried running the `drogon-core` test locally and ran into an issue with `20201022 18:14:14.172420 UTC 6 FATAL Socket fd < 0, Usually this is because the number of files opened by the program exceeds the system limit. Please use the ulimit command to check. - PgBatchConnection.cc:87` which may indicate that I am starting the database container with incorrect `ulimits`, so I will update such that the database is started the same way as the legacy toolset starts it and retest. This may take a while, and is completely unrelated, I strongly suspect, to the issue you are encountering.

--

Okay, after digging a bit, this one is strange. For one, the output should *not* say "roughly" because it is doing a strict equivalence check and if there were fewer *selects* than expected, this error will be displayed. As such, I am changing that language to "at least" to help indicate the intent better.

Some database implementations (and I do not remember which) over-report the number of queries run [for reasons] and so we only check that *at least* the known number of required selects have been executed. From your first example, I expect `concurrency` to be 8 with 8 cores to make `64*20` select calls *twice*, or `2,560` total `SELECT`s; however, your screenshot clearly shows that `2747` `SELECT`s were counted, hence the pass. The second screenshot *should* indicate `8 * 9 * 20 * 2` or `2880` `SELECT`s, which you do fine at `2887`, but the toolset is only reporting `714` of `720`. This strongly indicates a bug in the verifier code. I'll keep digging.

--

> I think it is likely something to do with the concurrency on the thread pool - maybe a race condition? i am not that very familiar with rust so hard to tell without some further digging.

I do not believe this to be the case. I have tested Gemini this with my 32-core machine and all levels of concurrency and it appears (both logically and in practice) to avoid races via atomic operations. At a high level, it sets an atomic reference to a mutex count of requests to be made. This count is the value against which we are verifying (the "... of roughly {} expected." value).

What this block does is spread the work over all the cpus available, makes a request to the end-point, and atomically increments a success count or a failure count based on the response while atomically decrementing the number of requests remaining to be made. As an example, on a dual-core machine with `concurrency` of 8, it would queue up 16 requests to make to the end-point. With verification the query string queries value is `20`, so there are going to be a minimum (though, it should be equal) of 320 `SELECT` queries run.

**Comment by billywhizz** [comment]
thanks for the update. i will see if i can gain any insight on this end. btw - the code i used for my test was the 0.1.0 release of TFBToolset. I got an error trying to run latest master.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/docker/docker_config.rs:137:34
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: tfb_toolset::benchmarker::Benchmarker::new
  15: tfb_toolset::cli::run
  16: tfb_toolset::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  20: std::panicking::try
             at src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

i can do some further digging here. is there an easy way for me to run the verifier locally also? at moment i think the toolset uses a dockerised version of the verifier.

**Comment by billywhizz** [comment]
the error above i see on master branch of TFBToolset seems to be a missing default here: https://github.com/TechEmpower/TFBToolset/blob/master/src/options.rs#L93

**Comment by msmith-techempower** [comment]
Yeah, I introduced a bug into the codebase - better to stick with the versioned releases until it is more stable.

**Comment by billywhizz** [comment]
i have had a look at the code in more detail and done some more testing. i think the issue is this line: https://github.com/TechEmpower/TFBVerifier/blob/master/src/test_type/query/updates.rs#L43.

for frameworks where the updates are all done in a single query then expected_updates should equal expected_rows / 20, i.e. the code should look like this (or whatever the correct syntax is for truncating a number in rust):

```
        let repetitions = 2;
        let concurrency = *self.concurrency_levels.iter().max().unwrap();
        let expected_rows = 20 * repetitions * concurrency;
        let expected_selects = expected_rows;
        let expected_updates = (expected_rows / 20).ceil();
        let expected_queries = expected_selects + expected_updates;
        let min = 1;
        let max = 500;
``` 

i'm still trying to figure out why i am seeing so many http request when testing with different concurrency levels but i am pretty sure regardless of what i find that the change above needs to be made in order for frameworks that do the updates in a single query to be verified.

**Comment by billywhizz** [comment]
hi @msmith-techempower. i have created a pull request here: https://github.com/TechEmpower/TFBVerifier/pull/5. i tested this locally and it resolves the verification issues i was having. sorry for leading you down the wrong path and assuming a bug. it seems it just needs a change to how it verifies the frameworks that do bulk updates.

**Comment by msmith-techempower** [comment]
Ah, I think I see the problem.

These are legacy variable names and I really should have attempt to better define what each of these does at every step.

The number of requests made to the server is going to be `repetitions * concurrency`, and we expect that every request to an `update` end-point must make `20 *` the `SELECT` calls to the database to read the correct number of rows. For example, at `concurrency=1` we expect 40 `SELECT`s to occur. Similarly, we expect that about 40 rows will be updated once the smoke clears.

However, the number of queries run against the server could be much lower than that because of the allowance of bulk updates. While from the above example we expect 40 selects and 40 rows to be updated, we may have only run 41 queries (40 selects and 1 bulk update).

I will continue fiddling with this, but I expect that you are correct and that I am being overly aggressive in testing the number of queries being executed on the database for this specific test.

**Comment by billywhizz** [comment]
@msmith-techempower yes i think you have nailed it there. in the case where we do bulk updates and concurrency = 1 (assuming 2 repetitions where N=20) then we would have 40 selects, 40 rows updated and 42 queries (40 select queries and 2 update queries that modify 20 rows each). with an individual query for each update the queries would be 80 (40 select queries and 40 update queries). i think the change i suggested above should resolve the issue.

**Comment by msmith-techempower** [comment]
I have pushed the newly built `techempower/tfb.verifier` image to DockerHub, so subsequent tests run normally with the toolset should pull and use the latest image.
